package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class SecurityService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public String  addUser(User user){
       user =userRepository.save(user);
        return user.getId();
    }
    public ArrayList<User> getAllUsers()
    {
        return (ArrayList<User>) userRepository.findAll();


    }
    public String login(User user){
        user  = userRepository.findByUsernameAndPassword(user.getUsername(),user.getPassword());
        System.out.println(user);
        if(user!=null)
        return "Success!";
        else
            return "login failure";
    }
    public String checkUserExists(User user){
        user = userRepository.findByUsername(user.getUsername());
        if(user!=null)
        {
            return "success!";
        }
        else
        {
            return "User does not exist";
        }
    }
    public String resetPassword(User newuser)
    {
        System.out.println("before save" +newuser);
        User existingUser = userRepository.findByUsername(newuser.getUsername());
        System.out.println("After finding by username " +existingUser);
        existingUser.setPassword(newuser.getPassword());
        existingUser = userRepository.save(existingUser);
        System.out.println("After save" +existingUser);

        return "pwd reset success!";
    }

}

